language: node_js
node_js: 13
install:
  - npm ci
  - cd server-api
  - npm ci
  - cd ../client-app
  - npm ci
  - cd ..
  - npm install -g codecov
before_script:
  - psql -c "create database travis_ci_test;" -U postgres

script:
  - npm run initdb && npm run test
  - codecov
services:
  - postgresql

after_success:
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash)
